-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 18:54:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_blackbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_blackbook
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `db_blackbook` DEFAULT CHARACTER
SET utf8
COLLATE utf8_general_mysql500_ci ;
USE `db_blackbook`
;

-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_cargo` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_cargo`
(
  `pk_cargo` INT
(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_cargo` VARCHAR
(60) NOT NULL,
  PRIMARY KEY
(`pk_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_funcionario` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_funcionario`
(
  `pk_funcionario` INT
(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_funcionario` VARCHAR
(60) NOT NULL,
  `nu_cpf` BIGINT
(11) UNSIGNED ZEROFILL NOT NULL,
  `email` VARCHAR
(45) NOT NULL,
  `telefone` BIGINT
(11) UNSIGNED NOT NULL,
  `senha` VARCHAR
(255) NOT NULL,
  `fk_cargo` INT
(2) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_funcionario`),
  CONSTRAINT `fk_tb_funcionario_tb_cargo1`
    FOREIGN KEY
(`fk_cargo`)
    REFERENCES `db_blackbook`.`tb_cargo`
(`pk_cargo`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nu_cpf_UNIQUE` ON `db_blackbook`.`tb_funcionario`
(`nu_cpf`);

CREATE INDEX `fk_tb_funcionario_tb_cargo1_idx` ON `db_blackbook`.`tb_funcionario`
(`fk_cargo`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_fornecedor` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_fornecedor`
(
  `pk_fornecedor` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_fornecedor` VARCHAR
(45) NOT NULL,
  `email` VARCHAR
(45) NULL,
  `telefone` INT
(14) NULL,
  PRIMARY KEY
(`pk_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_compra` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_compra`
(
  `pk_compra` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nu_valor` DECIMAL
(8,2) UNSIGNED NOT NULL,
  `dt_compra` DATE NOT NULL,
  `fk_fornecedor` INT
(8) UNSIGNED NOT NULL,
  `fk_funcionario_solicitante` INT
(3) UNSIGNED NOT NULL,
  `fk_funcionario_movimentacao` INT
(3) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_compra`),
  CONSTRAINT `fk_tb_compra_tb_fornecedor1`
    FOREIGN KEY
(`fk_fornecedor`)
    REFERENCES `db_blackbook`.`tb_fornecedor`
(`pk_fornecedor`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compra_tb_funcionario1`
    FOREIGN KEY
(`fk_funcionario_solicitante`)
    REFERENCES `db_blackbook`.`tb_funcionario`
(`pk_funcionario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compra_tb_funcionario2`
    FOREIGN KEY
(`fk_funcionario_movimentacao`)
    REFERENCES `db_blackbook`.`tb_funcionario`
(`pk_funcionario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_compra_tb_fornecedor1_idx` ON `db_blackbook`.`tb_compra`
(`fk_fornecedor`);

CREATE INDEX `fk_tb_compra_tb_funcionario1_idx` ON `db_blackbook`.`tb_compra`
(`fk_funcionario_solicitante`);

CREATE INDEX `fk_tb_compra_tb_funcionario2_idx` ON `db_blackbook`.`tb_compra`
(`fk_funcionario_movimentacao`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_categoria` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_categoria`
(
  `pk_categoria` INT
(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_categoria` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`pk_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_produto` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_produto`
(
  `pk_produto` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_produto` VARCHAR
(60) NOT NULL,
  `descricao` VARCHAR
(45) NULL,
  `qtd_minima` INT UNSIGNED NOT NULL,
  `qtd_total` INT UNSIGNED NOT NULL,
  `fk_categoria` INT
(2) UNSIGNED NOT NULL,
  `fk_fornecedor` INT
(8) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_produto`),
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY
(`fk_categoria`)
    REFERENCES `db_blackbook`.`tb_categoria`
(`pk_categoria`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_fornecedor1`
    FOREIGN KEY
(`fk_fornecedor`)
    REFERENCES `db_blackbook`.`tb_fornecedor`
(`pk_fornecedor`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_produto_tb_categoria_idx` ON `db_blackbook`.`tb_produto`
(`fk_categoria`);

CREATE INDEX `fk_tb_produto_tb_fornecedor1_idx` ON `db_blackbook`.`tb_produto`
(`fk_fornecedor`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_item_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_item_compra` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_item_compra`
(
  `pk_item_compra` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_entrada` DATETIME NOT NULL,
  `qtd_item` INT
(4) UNSIGNED NOT NULL,
  `fk_produto` INT
(8) UNSIGNED NOT NULL,
  `fk_compra` INT
(8) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_item_compra`),
  CONSTRAINT `fk_tb_item_compra_tb_produto1`
    FOREIGN KEY
(`fk_produto`)
    REFERENCES `db_blackbook`.`tb_produto`
(`pk_produto`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_compra_tb_compra1`
    FOREIGN KEY
(`fk_compra`)
    REFERENCES `db_blackbook`.`tb_compra`
(`pk_compra`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_item_compra_tb_produto1_idx` ON `db_blackbook`.`tb_item_compra`
(`fk_produto`);

CREATE INDEX `fk_tb_item_compra_tb_compra1_idx` ON `db_blackbook`.`tb_item_compra`
(`fk_compra`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_requisicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_requisicao` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_requisicao`
(
  `pk_requisicao` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_requisicao` DATE NOT NULL,
  `fk_funcionario_solicitante` INT
(3) UNSIGNED NOT NULL,
  `fk_funcionario_movimentacao` INT
(3) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_requisicao`),
  CONSTRAINT `fk_tb_requisicao_tb_funcionario1`
    FOREIGN KEY
(`fk_funcionario_solicitante`)
    REFERENCES `db_blackbook`.`tb_funcionario`
(`pk_funcionario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_requisicao_tb_funcionario2`
    FOREIGN KEY
(`fk_funcionario_movimentacao`)
    REFERENCES `db_blackbook`.`tb_funcionario`
(`pk_funcionario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_requisicao_tb_funcionario1_idx` ON `db_blackbook`.`tb_requisicao`
(`fk_funcionario_solicitante`);

CREATE INDEX `fk_tb_requisicao_tb_funcionario2_idx` ON `db_blackbook`.`tb_requisicao`
(`fk_funcionario_movimentacao`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_item_requisicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_item_requisicao` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_item_requisicao`
(
  `pk_item_requisicao` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtd_item` INT
(4) UNSIGNED NOT NULL,
  `fk_requisicao` INT
(8) UNSIGNED NOT NULL,
  `fk_produto` INT
(8) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_item_requisicao`),
  CONSTRAINT `fk_tb_item_requisicao_tb_requisicao1`
    FOREIGN KEY
(`fk_requisicao`)
    REFERENCES `db_blackbook`.`tb_requisicao`
(`pk_requisicao`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_requisicao_tb_produto1`
    FOREIGN KEY
(`fk_produto`)
    REFERENCES `db_blackbook`.`tb_produto`
(`pk_produto`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_item_requisicao_tb_requisicao1_idx` ON `db_blackbook`.`tb_item_requisicao`
(`fk_requisicao`);

CREATE INDEX `fk_tb_item_requisicao_tb_produto1_idx` ON `db_blackbook`.`tb_item_requisicao`
(`fk_produto`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_lote` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_lote`
(
  `pk_lote` INT
(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_fabricacao` DATE NOT NULL,
  `lote` VARCHAR
(20) NOT NULL,
  `data_validade` DATE NOT NULL,
  `valor_item` DECIMAL
(8,2) UNSIGNED NOT NULL,
  `fk_produto` INT
(8) UNSIGNED NOT NULL,
  PRIMARY KEY
(`pk_lote`),
  CONSTRAINT `fk_tb_lote_tb_produto1`
    FOREIGN KEY
(`fk_produto`)
    REFERENCES `db_blackbook`.`tb_produto`
(`pk_produto`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_lote_tb_produto1_idx` ON `db_blackbook`.`tb_lote`
(`fk_produto`);


-- -----------------------------------------------------
-- Table `db_blackbook`.`tb_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blackbook`.`tb_token` ;

CREATE TABLE
IF NOT EXISTS `db_blackbook`.`tb_token`
(
  `pk_token` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR
(1000) NOT NULL,
  `refresh_token` VARCHAR
(1000) NOT NULL,
  `expire_at` DATETIME NOT NULL,
  `fk_funcionario` INT UNSIGNED NOT NULL,
  `active` TINYINT
(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY
(`pk_token`),
  CONSTRAINT `fk_tb_token_tb_funcionario`
    FOREIGN KEY
(`fk_funcionario`)
    REFERENCES `db_blackbook`.`tb_funcionario`
(`pk_funcionario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `pk_funcionario_idx` ON `db_blackbook`.`tb_token`
(`fk_funcionario`);


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
